#INSTALLATION
install.packages('devtools')
source("https://bioconductor.org/biocLite.R")
biocLite("annotate")
biocLite("Biostrings")
library(devtools)
install_github("mhahsler/rBLAST")
library(annotate)
library(Biostrings) #DNAStringSet Object
library(rBLAST)
install_github("mhahsler/rMSA")
library(rMSA)
library(magrittr)
library(ape) #read.dna
install.packages(c('data.table','plyr','seqinr','lubridate','downloader','R.utils','gridExtra','RCurl'))
library(data.table)
library(seqinr)
library(lubridate)
library(downloader)
library(R.utils)
library(RCurl)
library(magrittr)
library(gridExtra)
library(plyr)
library(taxize)
